In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files

uploaded = files.upload()

Saving newborn_health_monitoring_with_risk.csv to newborn_health_monitoring_with_risk (1).csv

In [4]:
df = pd.read_csv("newborn_health_monitoring_with_risk.csv")
df

,baby_id,name,gender,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,date,age_days,weight_kg,...,oxygen_saturation,feeding_type,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score,immunizations_done,reflexes_normal,risk_level
0,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-10,1,3.28,...,98,Formula,11,9,0,4.2,7.0,Yes,Yes,At Risk
1,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-11,2,3.35,...,99,Formula,11,5,2,10.6,NaN,No,No,At Risk
2,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-12,3,3.35,...,97,Breastfeeding,7,6,5,9.8,NaN,No,No,Healthy
3,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-13,4,3.48,...,97,Mixed,11,8,4,8.1,NaN,No,Yes,Healthy
4,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-14,5,3.50,...,96,Breastfeeding,11,7,1,11.6,NaN,No,Yes,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-03-31,26,5.29,...,96,Formula,8,7,4,4.0,NaN,No,Yes,Healthy
2996,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-01,27,5.23,...,98,Breastfeeding,7,6,1,2.4,NaN,No,Yes,Healthy
2997,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-02,28,5.29,...,98,Breastfeeding,8,4,1,3.6,NaN,No,Yes,Healthy
2998,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-03,29,5.39,...,97,Mixed,10,5,2,2.2,NaN,No,No,Healthy
2999,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-04,30,5.41,...,97,Mixed,9,7,1,3.0,NaN,Yes,Yes,Healthy

In [5]:
df.isnull().sum()

baby_id                           0
name                              0
gender                            0
gestational_age_weeks             0
birth_weight_kg                   0
birth_length_cm                   0
birth_head_circumference_cm       0
date                              0
age_days                          0
weight_kg                         0
length_cm                         0
head_circumference_cm             0
temperature_c                     0
heart_rate_bpm                    0
respiratory_rate_bpm              0
oxygen_saturation                 0
feeding_type                      0
feeding_frequency_per_day         0
urine_output_count                0
stool_count                       0
jaundice_level_mg_dl              0
apgar_score                    2900
immunizations_done                0
reflexes_normal                   0
risk_level                        0
dtype: int64

In [6]:
df.head()

,baby_id,name,gender,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,date,age_days,weight_kg,...,oxygen_saturation,feeding_type,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score,immunizations_done,reflexes_normal,risk_level
0,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-10,1,3.28,...,98,Formula,11,9,0,4.2,7.0,Yes,Yes,At Risk
1,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-11,2,3.35,...,99,Formula,11,5,2,10.6,NaN,No,No,At Risk
2,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-12,3,3.35,...,97,Breastfeeding,7,6,5,9.8,NaN,No,No,Healthy
3,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-13,4,3.48,...,97,Mixed,11,8,4,8.1,NaN,No,Yes,Healthy
4,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-14,5,3.50,...,96,Breastfeeding,11,7,1,11.6,NaN,No,Yes,At Risk

In [7]:
df.shape

(3000, 25)

In [8]:
df.columns

Index(['baby_id', 'name', 'gender', 'gestational_age_weeks', 'birth_weight_kg',
       'birth_length_cm', 'birth_head_circumference_cm', 'date', 'age_days',
       'weight_kg', 'length_cm', 'head_circumference_cm', 'temperature_c',
       'heart_rate_bpm', 'respiratory_rate_bpm', 'oxygen_saturation',
       'feeding_type', 'feeding_frequency_per_day', 'urine_output_count',
       'stool_count', 'jaundice_level_mg_dl', 'apgar_score',
       'immunizations_done', 'reflexes_normal', 'risk_level'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   baby_id                      3000 non-null   object
 1   name                         3000 non-null   object
 2   gender                       3000 non-null   object
 3   gestational_age_weeks        3000 non-null   float64
 4   birth_weight_kg              3000 non-null   float64
 5   birth_length_cm              3000 non-null   float64
 6   birth_head_circumference_cm  3000 non-null   float64
 7   date                         3000 non-null   object
 8   age_days                     3000 non-null   int64
 9   weight_kg                    3000 non-null   float64
 10  length_cm                    3000 non-null   float64
 11  head_circumference_cm        3000 non-null   float64
 12  temperature_c                3000 non-null   float64
 13  heart_rate_bpm               3000 non-null   int64
 14  respiratory_rate_bpm         3000 non-null   int64
 15  oxygen_saturation            3000 non-null   int64
 16  feeding_type                 3000 non-null   object
 17  feeding_frequency_per_day    3000 non-null   int64
 18  urine_output_count           3000 non-null   int64
 19  stool_count                  3000 non-null   int64
 20  jaundice_level_mg_dl         3000 non-null   float64
 21  apgar_score                  100 non-null    float64
 22  immunizations_done           3000 non-null   object
 23  reflexes_normal              3000 non-null   object
 24  risk_level                   3000 non-null   object
dtypes: float64(10), int64(7), object(8)
memory usage: 586.1+ KB

In [10]:
df.describe()

,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,age_days,weight_kg,length_cm,head_circumference_cm,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,100.000000
mean,38.878000,3.205000,49.727000,34.128000,15.500000,3.669730,50.508000,34.438900,37.002933,139.682000,39.421333,97.473000,9.450000,6.470000,2.448333,4.163467,8.400000
std,1.570076,0.561555,2.145065,1.486254,8.656884,0.621355,2.196846,1.500893,0.310747,10.139386,4.999481,1.048318,1.707182,1.700803,1.699106,2.861971,1.163415
min,35.400000,1.860000,45.100000,31.200000,1.000000,1.790000,45.000000,31.100000,35.800000,100.000000,23.000000,94.000000,7.000000,4.000000,0.000000,0.000000,7.000000
25%,37.800000,2.870000,48.475000,32.975000,8.000000,3.220000,49.100000,33.300000,36.800000,133.000000,36.000000,97.000000,8.000000,5.000000,1.000000,2.500000,7.000000
50%,38.800000,3.165000,49.550000,34.100000,15.500000,3.660000,50.400000,34.400000,37.000000,140.000000,39.000000,97.000000,9.000000,6.000000,2.000000,3.300000,8.000000
75%,40.100000,3.625000,51.025000,34.800000,23.000000,4.100000,51.800000,35.300000,37.200000,146.000000,43.000000,98.000000,11.000000,8.000000,4.000000,4.300000,9.250000
max,43.000000,4.470000,55.800000,38.100000,30.000000,5.410000,57.400000,38.700000,38.100000,173.000000,57.000000,101.000000,12.000000,9.000000,5.000000,15.000000,10.000000

In [11]:
df.isnull().sum()

baby_id                           0
name                              0
gender                            0
gestational_age_weeks             0
birth_weight_kg                   0
birth_length_cm                   0
birth_head_circumference_cm       0
date                              0
age_days                          0
weight_kg                         0
length_cm                         0
head_circumference_cm             0
temperature_c                     0
heart_rate_bpm                    0
respiratory_rate_bpm              0
oxygen_saturation                 0
feeding_type                      0
feeding_frequency_per_day         0
urine_output_count                0
stool_count                       0
jaundice_level_mg_dl              0
apgar_score                    2900
immunizations_done                0
reflexes_normal                   0
risk_level                        0
dtype: int64

In [12]:
(df.isnull().sum()/len(df))*100

baby_id                         0.000000
name                            0.000000
gender                          0.000000
gestational_age_weeks           0.000000
birth_weight_kg                 0.000000
birth_length_cm                 0.000000
birth_head_circumference_cm     0.000000
date                            0.000000
age_days                        0.000000
weight_kg                       0.000000
length_cm                       0.000000
head_circumference_cm           0.000000
temperature_c                   0.000000
heart_rate_bpm                  0.000000
respiratory_rate_bpm            0.000000
oxygen_saturation               0.000000
feeding_type                    0.000000
feeding_frequency_per_day       0.000000
urine_output_count              0.000000
stool_count                     0.000000
jaundice_level_mg_dl            0.000000
apgar_score                    96.666667
immunizations_done              0.000000
reflexes_normal                 0.000000
risk_level                      0.000000
dtype: float64

In [13]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
print(num_cols)

Index(['gestational_age_weeks', 'birth_weight_kg', 'birth_length_cm',
       'birth_head_circumference_cm', 'age_days', 'weight_kg', 'length_cm',
       'head_circumference_cm', 'temperature_c', 'heart_rate_bpm',
       'respiratory_rate_bpm', 'oxygen_saturation',
       'feeding_frequency_per_day', 'urine_output_count', 'stool_count',
       'jaundice_level_mg_dl', 'apgar_score'],
      dtype='object')

In [14]:
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [15]:
cat_cols = df.select_dtypes(include=['object']).columns
print(cat_cols)

Index(['baby_id', 'name', 'gender', 'date', 'feeding_type',
       'immunizations_done', 'reflexes_normal', 'risk_level'],
      dtype='object')

In [16]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.dtypes

baby_id                         object
name                            object
gender                          object
gestational_age_weeks          float64
birth_weight_kg                float64
birth_length_cm                float64
birth_head_circumference_cm    float64
date                            object
age_days                         int64
weight_kg                      float64
length_cm                      float64
head_circumference_cm          float64
temperature_c                  float64
heart_rate_bpm                   int64
respiratory_rate_bpm             int64
oxygen_saturation                int64
feeding_type                    object
feeding_frequency_per_day        int64
urine_output_count               int64
stool_count                      int64
jaundice_level_mg_dl           float64
apgar_score                    float64
immunizations_done              object
reflexes_normal                 object
risk_level                      object
dtype: object

In [20]:
df.drop("baby_id", axis=1, inplace=True)

In [21]:
df.select_dtypes(include='object').columns

Index(['name', 'gender', 'date', 'feeding_type', 'immunizations_done',
       'reflexes_normal', 'risk_level'],
      dtype='object')

In [22]:
df.describe()

,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,age_days,weight_kg,length_cm,head_circumference_cm,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,38.878000,3.205000,49.727000,34.128000,15.500000,3.669730,50.508000,34.438900,37.002933,139.682000,39.421333,97.473000,9.450000,6.470000,2.448333,4.163467,8.013333
std,1.570076,0.561555,2.145065,1.486254,8.656884,0.621355,2.196846,1.500893,0.310747,10.139386,4.999481,1.048318,1.707182,1.700803,1.699106,2.861971,0.223246
min,35.400000,1.860000,45.100000,31.200000,1.000000,1.790000,45.000000,31.100000,35.800000,100.000000,23.000000,94.000000,7.000000,4.000000,0.000000,0.000000,7.000000
25%,37.800000,2.870000,48.475000,32.975000,8.000000,3.220000,49.100000,33.300000,36.800000,133.000000,36.000000,97.000000,8.000000,5.000000,1.000000,2.500000,8.000000
50%,38.800000,3.165000,49.550000,34.100000,15.500000,3.660000,50.400000,34.400000,37.000000,140.000000,39.000000,97.000000,9.000000,6.000000,2.000000,3.300000,8.000000
75%,40.100000,3.625000,51.025000,34.800000,23.000000,4.100000,51.800000,35.300000,37.200000,146.000000,43.000000,98.000000,11.000000,8.000000,4.000000,4.300000,8.000000
max,43.000000,4.470000,55.800000,38.100000,30.000000,5.410000,57.400000,38.700000,38.100000,173.000000,57.000000,101.000000,12.000000,9.000000,5.000000,15.000000,10.000000

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [24]:
df[num_cols] = scaler.fit_transform(df[num_cols])

In [25]:
df.head()

,name,gender,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,date,age_days,weight_kg,length_cm,...,oxygen_saturation,feeding_type,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score,immunizations_done,reflexes_normal,risk_level
0,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-10,-1.675247,-0.627331,-0.185752,...,0.502794,Formula,0.908080,1.487781,-1.441194,0.012767,-4.539842,Yes,Yes,At Risk
1,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-11,-1.559712,-0.514655,-0.140224,...,1.456862,Formula,0.908080,-0.864442,-0.263908,2.249361,-0.059735,No,No,At Risk
2,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-12,-1.444178,-0.514655,0.041885,...,-0.451274,Breastfeeding,-1.435353,-0.276386,1.502021,1.969787,-0.059735,No,No,Healthy
3,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-13,-1.328644,-0.305400,-0.094697,...,-0.451274,Mixed,0.908080,0.899725,0.913378,1.375692,-0.059735,No,Yes,Healthy
4,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-14,-1.213110,-0.273207,-0.094697,...,-1.405342,Breastfeeding,0.908080,0.311669,-0.852551,2.598829,-0.059735,No,Yes,At Risk

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         3000 non-null   object
 1   gender                       3000 non-null   object
 2   gestational_age_weeks        3000 non-null   float64
 3   birth_weight_kg              3000 non-null   float64
 4   birth_length_cm              3000 non-null   float64
 5   birth_head_circumference_cm  3000 non-null   float64
 6   date                         3000 non-null   object
 7   age_days                     3000 non-null   float64
 8   weight_kg                    3000 non-null   float64
 9   length_cm                    3000 non-null   float64
 10  head_circumference_cm        3000 non-null   float64
 11  temperature_c                3000 non-null   float64
 12  heart_rate_bpm               3000 non-null   float64
 13  respiratory_rate_bpm         3000 non-null   float64
 14  oxygen_saturation            3000 non-null   float64
 15  feeding_type                 3000 non-null   object
 16  feeding_frequency_per_day    3000 non-null   float64
 17  urine_output_count           3000 non-null   float64
 18  stool_count                  3000 non-null   float64
 19  jaundice_level_mg_dl         3000 non-null   float64
 20  apgar_score                  3000 non-null   float64
 21  immunizations_done           3000 non-null   object
 22  reflexes_normal              3000 non-null   object
 23  risk_level                   3000 non-null   object
dtypes: float64(17), object(7)
memory usage: 562.6+ KB

In [27]:
columns_to_drop = ['gestational_age_weeks', 'birth_weight_kg', 'birth_length_cm', 'birth_head_circumference_cm', 'age_days', 'length_cm', 'head_circumference_cm', 'feeding_frequency_per_day', 'urine_output_count', 'stool_count', 'jaundice_level_mg_dl']
df.drop(columns=columns_to_drop, inplace=True)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  3000 non-null   object
 1   gender                3000 non-null   object
 2   date                  3000 non-null   object
 3   weight_kg             3000 non-null   float64
 4   temperature_c         3000 non-null   float64
 5   heart_rate_bpm        3000 non-null   float64
 6   respiratory_rate_bpm  3000 non-null   float64
 7   oxygen_saturation     3000 non-null   float64
 8   feeding_type          3000 non-null   object
 9   apgar_score           3000 non-null   float64
 10  immunizations_done    3000 non-null   object
 11  reflexes_normal       3000 non-null   object
 12  risk_level            3000 non-null   object
dtypes: float64(6), object(7)
memory usage: 304.8+ KB

In [29]:
df.isnull().sum()

name                    0
gender                  0
date                    0
weight_kg               0
temperature_c           0
heart_rate_bpm          0
respiratory_rate_bpm    0
oxygen_saturation       0
feeding_type            0
apgar_score             0
immunizations_done      0
reflexes_normal         0
risk_level              0
dtype: int64

In [30]:
X = df.drop("risk_level", axis=1)
y = df["risk_level"]

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [32]:
df

,name,gender,date,weight_kg,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,feeding_type,apgar_score,immunizations_done,reflexes_normal,risk_level
0,Sara,Female,2024-12-10,-0.627331,-0.009441,2.004203,-0.684452,0.502794,Formula,-4.539842,Yes,Yes,At Risk
1,Sara,Female,2024-12-11,-0.514655,0.634277,1.609636,0.115765,1.456862,Formula,-0.059735,No,No,At Risk
2,Sara,Female,2024-12-12,-0.514655,0.312418,-0.264557,-0.484398,-0.451274,Breastfeeding,-0.059735,No,No,Healthy
3,Sara,Female,2024-12-13,-0.305400,1.277995,-0.955049,-1.284614,-0.451274,Mixed,-0.059735,No,Yes,Healthy
4,Sara,Female,2024-12-14,-0.273207,-0.653159,-0.165915,-0.084289,-1.405342,Breastfeeding,-0.059735,No,Yes,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Brian,Male,2025-03-31,2.608076,-0.975018,-1.448258,0.915981,-1.405342,Formula,-0.059735,No,Yes,Healthy
2996,Brian,Male,2025-04-01,2.511497,-0.009441,-0.165915,-1.684722,0.502794,Breastfeeding,-0.059735,No,Yes,Healthy
2997,Brian,Male,2025-04-02,2.608076,-0.653159,0.327293,0.515873,0.502794,Breastfeeding,-0.059735,No,Yes,Healthy
2998,Brian,Male,2025-04-03,2.769042,1.277995,-2.040109,2.516414,-0.451274,Mixed,-0.059735,No,No,Healthy
2999,Brian,Male,2025-04-04,2.801235,-0.009441,0.425935,0.115765,-0.451274,Mixed,-0.059735,Yes,Yes,Healthy

In [33]:
df.isnull().sum()

name                    0
gender                  0
date                    0
weight_kg               0
temperature_c           0
heart_rate_bpm          0
respiratory_rate_bpm    0
oxygen_saturation       0
feeding_type            0
apgar_score             0
immunizations_done      0
reflexes_normal         0
risk_level              0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.drop_duplicates(inplace=True)

In [36]:
df.drop("name", axis=1, inplace=True)

In [37]:
df.drop("date", axis=1, inplace=True)

In [38]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["gender"] = le.fit_transform(df["gender"])

In [39]:
df["immunizations_done"] = le.fit_transform(df["immunizations_done"])

In [40]:
df["reflexes_normal"] = le.fit_transform(df["reflexes_normal"])

In [41]:
df = pd.get_dummies(df,
                    columns=["feeding_type"],
                    dtype=int)

In [42]:
df["risk_level"] = le.fit_transform(df["risk_level"])

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   gender                      3000 non-null   int64
 1   weight_kg                   3000 non-null   float64
 2   temperature_c               3000 non-null   float64
 3   heart_rate_bpm              3000 non-null   float64
 4   respiratory_rate_bpm        3000 non-null   float64
 5   oxygen_saturation           3000 non-null   float64
 6   apgar_score                 3000 non-null   float64
 7   immunizations_done          3000 non-null   int64
 8   reflexes_normal             3000 non-null   int64
 9   risk_level                  3000 non-null   int64
 10  feeding_type_Breastfeeding  3000 non-null   int64
 11  feeding_type_Formula        3000 non-null   int64
 12  feeding_type_Mixed          3000 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 304.8 KB

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X = df.drop("risk_level", axis=1)
y = df["risk_level"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [46]:
df.columns

Index(['gender', 'weight_kg', 'temperature_c', 'heart_rate_bpm',
       'respiratory_rate_bpm', 'oxygen_saturation', 'apgar_score',
       'immunizations_done', 'reflexes_normal', 'risk_level',
       'feeding_type_Breastfeeding', 'feeding_type_Formula',
       'feeding_type_Mixed'],
      dtype='object')

In [47]:
X = df.drop("risk_level", axis=1)

y = df["risk_level"]

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [49]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2400, 12)
(600, 12)
(2400,)
(600,)

In [50]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [51]:
y_pred = model.predict(X_test)

In [52]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9116666666666666

Classification Report:

              precision    recall  f1-score   support

           0       0.97      0.35      0.51        80
           1       0.91      1.00      0.95       520

    accuracy                           0.91       600
   macro avg       0.94      0.67      0.73       600
weighted avg       0.92      0.91      0.89       600


Confusion Matrix:

[[ 28  52]
 [  1 519]]