In [5]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files

uploaded = files.upload()

Saving newborn_health_monitoring_with_risk.csv to newborn_health_monitoring_with_risk.csv

In [4]:
df = pd.read_csv("newborn_health_monitoring_with_risk.csv")
df

,baby_id,name,gender,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,date,age_days,weight_kg,...,oxygen_saturation,feeding_type,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score,immunizations_done,reflexes_normal,risk_level
0,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-10,1,3.28,...,98,Formula,11,9,0,4.2,7.0,Yes,Yes,At Risk
1,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-11,2,3.35,...,99,Formula,11,5,2,10.6,NaN,No,No,At Risk
2,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-12,3,3.35,...,97,Breastfeeding,7,6,5,9.8,NaN,No,No,Healthy
3,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-13,4,3.48,...,97,Mixed,11,8,4,8.1,NaN,No,Yes,Healthy
4,B001,Sara,Female,40.2,3.30,50.0,31.9,2024-12-14,5,3.50,...,96,Breastfeeding,11,7,1,11.6,NaN,No,Yes,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-03-31,26,5.29,...,96,Formula,8,7,4,4.0,NaN,No,Yes,Healthy
2996,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-01,27,5.23,...,98,Breastfeeding,7,6,1,2.4,NaN,No,Yes,Healthy
2997,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-02,28,5.29,...,98,Breastfeeding,8,4,1,3.6,NaN,No,Yes,Healthy
2998,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-03,29,5.39,...,97,Mixed,10,5,2,2.2,NaN,No,No,Healthy
2999,B100,Brian,Male,39.1,4.47,50.8,36.3,2025-04-04,30,5.41,...,97,Mixed,9,7,1,3.0,NaN,Yes,Yes,Healthy

In [6]:
df.isnull().sum()

baby_id                           0
name                              0
gender                            0
gestational_age_weeks             0
birth_weight_kg                   0
birth_length_cm                   0
birth_head_circumference_cm       0
date                              0
age_days                          0
weight_kg                         0
length_cm                         0
head_circumference_cm             0
temperature_c                     0
heart_rate_bpm                    0
respiratory_rate_bpm              0
oxygen_saturation                 0
feeding_type                      0
feeding_frequency_per_day         0
urine_output_count                0
stool_count                       0
jaundice_level_mg_dl              0
apgar_score                    2900
immunizations_done                0
reflexes_normal                   0
risk_level                        0
dtype: int64

In [7]:
df.head()

,baby_id,name,gender,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,date,age_days,weight_kg,...,oxygen_saturation,feeding_type,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score,immunizations_done,reflexes_normal,risk_level
0,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-10,1,3.28,...,98,Formula,11,9,0,4.2,7.0,Yes,Yes,At Risk
1,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-11,2,3.35,...,99,Formula,11,5,2,10.6,NaN,No,No,At Risk
2,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-12,3,3.35,...,97,Breastfeeding,7,6,5,9.8,NaN,No,No,Healthy
3,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-13,4,3.48,...,97,Mixed,11,8,4,8.1,NaN,No,Yes,Healthy
4,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-14,5,3.50,...,96,Breastfeeding,11,7,1,11.6,NaN,No,Yes,At Risk

In [8]:
df.shape

(3000, 25)

In [9]:
df.columns

Index(['baby_id', 'name', 'gender', 'gestational_age_weeks', 'birth_weight_kg',
       'birth_length_cm', 'birth_head_circumference_cm', 'date', 'age_days',
       'weight_kg', 'length_cm', 'head_circumference_cm', 'temperature_c',
       'heart_rate_bpm', 'respiratory_rate_bpm', 'oxygen_saturation',
       'feeding_type', 'feeding_frequency_per_day', 'urine_output_count',
       'stool_count', 'jaundice_level_mg_dl', 'apgar_score',
       'immunizations_done', 'reflexes_normal', 'risk_level'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   baby_id                      3000 non-null   object
 1   name                         3000 non-null   object
 2   gender                       3000 non-null   object
 3   gestational_age_weeks        3000 non-null   float64
 4   birth_weight_kg              3000 non-null   float64
 5   birth_length_cm              3000 non-null   float64
 6   birth_head_circumference_cm  3000 non-null   float64
 7   date                         3000 non-null   object
 8   age_days                     3000 non-null   int64
 9   weight_kg                    3000 non-null   float64
 10  length_cm                    3000 non-null   float64
 11  head_circumference_cm        3000 non-null   float64
 12  temperature_c                3000 non-null   float64
 13  heart_rate_bpm               3000 non-null   int64
 14  respiratory_rate_bpm         3000 non-null   int64
 15  oxygen_saturation            3000 non-null   int64
 16  feeding_type                 3000 non-null   object
 17  feeding_frequency_per_day    3000 non-null   int64
 18  urine_output_count           3000 non-null   int64
 19  stool_count                  3000 non-null   int64
 20  jaundice_level_mg_dl         3000 non-null   float64
 21  apgar_score                  100 non-null    float64
 22  immunizations_done           3000 non-null   object
 23  reflexes_normal              3000 non-null   object
 24  risk_level                   3000 non-null   object
dtypes: float64(10), int64(7), object(8)
memory usage: 586.1+ KB

In [11]:
df.describe()

,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,age_days,weight_kg,length_cm,head_circumference_cm,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,100.000000
mean,38.878000,3.205000,49.727000,34.128000,15.500000,3.669730,50.508000,34.438900,37.002933,139.682000,39.421333,97.473000,9.450000,6.470000,2.448333,4.163467,8.400000
std,1.570076,0.561555,2.145065,1.486254,8.656884,0.621355,2.196846,1.500893,0.310747,10.139386,4.999481,1.048318,1.707182,1.700803,1.699106,2.861971,1.163415
min,35.400000,1.860000,45.100000,31.200000,1.000000,1.790000,45.000000,31.100000,35.800000,100.000000,23.000000,94.000000,7.000000,4.000000,0.000000,0.000000,7.000000
25%,37.800000,2.870000,48.475000,32.975000,8.000000,3.220000,49.100000,33.300000,36.800000,133.000000,36.000000,97.000000,8.000000,5.000000,1.000000,2.500000,7.000000
50%,38.800000,3.165000,49.550000,34.100000,15.500000,3.660000,50.400000,34.400000,37.000000,140.000000,39.000000,97.000000,9.000000,6.000000,2.000000,3.300000,8.000000
75%,40.100000,3.625000,51.025000,34.800000,23.000000,4.100000,51.800000,35.300000,37.200000,146.000000,43.000000,98.000000,11.000000,8.000000,4.000000,4.300000,9.250000
max,43.000000,4.470000,55.800000,38.100000,30.000000,5.410000,57.400000,38.700000,38.100000,173.000000,57.000000,101.000000,12.000000,9.000000,5.000000,15.000000,10.000000

In [12]:
df.isnull().sum()

baby_id                           0
name                              0
gender                            0
gestational_age_weeks             0
birth_weight_kg                   0
birth_length_cm                   0
birth_head_circumference_cm       0
date                              0
age_days                          0
weight_kg                         0
length_cm                         0
head_circumference_cm             0
temperature_c                     0
heart_rate_bpm                    0
respiratory_rate_bpm              0
oxygen_saturation                 0
feeding_type                      0
feeding_frequency_per_day         0
urine_output_count                0
stool_count                       0
jaundice_level_mg_dl              0
apgar_score                    2900
immunizations_done                0
reflexes_normal                   0
risk_level                        0
dtype: int64

In [13]:
(df.isnull().sum()/len(df))*100

baby_id                         0.000000
name                            0.000000
gender                          0.000000
gestational_age_weeks           0.000000
birth_weight_kg                 0.000000
birth_length_cm                 0.000000
birth_head_circumference_cm     0.000000
date                            0.000000
age_days                        0.000000
weight_kg                       0.000000
length_cm                       0.000000
head_circumference_cm           0.000000
temperature_c                   0.000000
heart_rate_bpm                  0.000000
respiratory_rate_bpm            0.000000
oxygen_saturation               0.000000
feeding_type                    0.000000
feeding_frequency_per_day       0.000000
urine_output_count              0.000000
stool_count                     0.000000
jaundice_level_mg_dl            0.000000
apgar_score                    96.666667
immunizations_done              0.000000
reflexes_normal                 0.000000
risk_level                      0.000000
dtype: float64

In [14]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
print(num_cols)

Index(['gestational_age_weeks', 'birth_weight_kg', 'birth_length_cm',
       'birth_head_circumference_cm', 'age_days', 'weight_kg', 'length_cm',
       'head_circumference_cm', 'temperature_c', 'heart_rate_bpm',
       'respiratory_rate_bpm', 'oxygen_saturation',
       'feeding_frequency_per_day', 'urine_output_count', 'stool_count',
       'jaundice_level_mg_dl', 'apgar_score'],
      dtype='object')

In [15]:
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [16]:
cat_cols = df.select_dtypes(include=['object']).columns
print(cat_cols)

Index(['baby_id', 'name', 'gender', 'date', 'feeding_type',
       'immunizations_done', 'reflexes_normal', 'risk_level'],
      dtype='object')

In [17]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.dtypes

baby_id                         object
name                            object
gender                          object
gestational_age_weeks          float64
birth_weight_kg                float64
birth_length_cm                float64
birth_head_circumference_cm    float64
date                            object
age_days                         int64
weight_kg                      float64
length_cm                      float64
head_circumference_cm          float64
temperature_c                  float64
heart_rate_bpm                   int64
respiratory_rate_bpm             int64
oxygen_saturation                int64
feeding_type                    object
feeding_frequency_per_day        int64
urine_output_count               int64
stool_count                      int64
jaundice_level_mg_dl           float64
apgar_score                    float64
immunizations_done              object
reflexes_normal                 object
risk_level                      object
dtype: object

In [21]:
df.drop("baby_id", axis=1, inplace=True)

In [22]:
df.select_dtypes(include='object').columns

Index(['name', 'gender', 'date', 'feeding_type', 'immunizations_done',
       'reflexes_normal', 'risk_level'],
      dtype='object')

In [23]:
df.describe()

,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,age_days,weight_kg,length_cm,head_circumference_cm,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,38.878000,3.205000,49.727000,34.128000,15.500000,3.669730,50.508000,34.438900,37.002933,139.682000,39.421333,97.473000,9.450000,6.470000,2.448333,4.163467,8.013333
std,1.570076,0.561555,2.145065,1.486254,8.656884,0.621355,2.196846,1.500893,0.310747,10.139386,4.999481,1.048318,1.707182,1.700803,1.699106,2.861971,0.223246
min,35.400000,1.860000,45.100000,31.200000,1.000000,1.790000,45.000000,31.100000,35.800000,100.000000,23.000000,94.000000,7.000000,4.000000,0.000000,0.000000,7.000000
25%,37.800000,2.870000,48.475000,32.975000,8.000000,3.220000,49.100000,33.300000,36.800000,133.000000,36.000000,97.000000,8.000000,5.000000,1.000000,2.500000,8.000000
50%,38.800000,3.165000,49.550000,34.100000,15.500000,3.660000,50.400000,34.400000,37.000000,140.000000,39.000000,97.000000,9.000000,6.000000,2.000000,3.300000,8.000000
75%,40.100000,3.625000,51.025000,34.800000,23.000000,4.100000,51.800000,35.300000,37.200000,146.000000,43.000000,98.000000,11.000000,8.000000,4.000000,4.300000,8.000000
max,43.000000,4.470000,55.800000,38.100000,30.000000,5.410000,57.400000,38.700000,38.100000,173.000000,57.000000,101.000000,12.000000,9.000000,5.000000,15.000000,10.000000

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [25]:
df[num_cols] = scaler.fit_transform(df[num_cols])

In [26]:
df.head()

,name,gender,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,date,age_days,weight_kg,length_cm,...,oxygen_saturation,feeding_type,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score,immunizations_done,reflexes_normal,risk_level
0,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-10,-1.675247,-0.627331,-0.185752,...,0.502794,Formula,0.908080,1.487781,-1.441194,0.012767,-4.539842,Yes,Yes,At Risk
1,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-11,-1.559712,-0.514655,-0.140224,...,1.456862,Formula,0.908080,-0.864442,-0.263908,2.249361,-0.059735,No,No,At Risk
2,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-12,-1.444178,-0.514655,0.041885,...,-0.451274,Breastfeeding,-1.435353,-0.276386,1.502021,1.969787,-0.059735,No,No,Healthy
3,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-13,-1.328644,-0.305400,-0.094697,...,-0.451274,Mixed,0.908080,0.899725,0.913378,1.375692,-0.059735,No,Yes,Healthy
4,Sara,Female,0.842138,0.169201,0.12729,-1.49932,2024-12-14,-1.213110,-0.273207,-0.094697,...,-1.405342,Breastfeeding,0.908080,0.311669,-0.852551,2.598829,-0.059735,No,Yes,At Risk

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         3000 non-null   object
 1   gender                       3000 non-null   object
 2   gestational_age_weeks        3000 non-null   float64
 3   birth_weight_kg              3000 non-null   float64
 4   birth_length_cm              3000 non-null   float64
 5   birth_head_circumference_cm  3000 non-null   float64
 6   date                         3000 non-null   object
 7   age_days                     3000 non-null   float64
 8   weight_kg                    3000 non-null   float64
 9   length_cm                    3000 non-null   float64
 10  head_circumference_cm        3000 non-null   float64
 11  temperature_c                3000 non-null   float64
 12  heart_rate_bpm               3000 non-null   float64
 13  respiratory_rate_bpm         3000 non-null   float64
 14  oxygen_saturation            3000 non-null   float64
 15  feeding_type                 3000 non-null   object
 16  feeding_frequency_per_day    3000 non-null   float64
 17  urine_output_count           3000 non-null   float64
 18  stool_count                  3000 non-null   float64
 19  jaundice_level_mg_dl         3000 non-null   float64
 20  apgar_score                  3000 non-null   float64
 21  immunizations_done           3000 non-null   object
 22  reflexes_normal              3000 non-null   object
 23  risk_level                   3000 non-null   object
dtypes: float64(17), object(7)
memory usage: 562.6+ KB

In [28]:
columns_to_drop = ['gestational_age_weeks', 'birth_weight_kg', 'birth_length_cm', 'birth_head_circumference_cm', 'age_days', 'length_cm', 'head_circumference_cm', 'feeding_frequency_per_day', 'urine_output_count', 'stool_count', 'jaundice_level_mg_dl']
df.drop(columns=columns_to_drop, inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  3000 non-null   object
 1   gender                3000 non-null   object
 2   date                  3000 non-null   object
 3   weight_kg             3000 non-null   float64
 4   temperature_c         3000 non-null   float64
 5   heart_rate_bpm        3000 non-null   float64
 6   respiratory_rate_bpm  3000 non-null   float64
 7   oxygen_saturation     3000 non-null   float64
 8   feeding_type          3000 non-null   object
 9   apgar_score           3000 non-null   float64
 10  immunizations_done    3000 non-null   object
 11  reflexes_normal       3000 non-null   object
 12  risk_level            3000 non-null   object
dtypes: float64(6), object(7)
memory usage: 304.8+ KB

In [30]:
df.isnull().sum()

name                    0
gender                  0
date                    0
weight_kg               0
temperature_c           0
heart_rate_bpm          0
respiratory_rate_bpm    0
oxygen_saturation       0
feeding_type            0
apgar_score             0
immunizations_done      0
reflexes_normal         0
risk_level              0
dtype: int64

In [31]:
X = df.drop("risk_level", axis=1)
y = df["risk_level"]

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [33]:
df

,name,gender,date,weight_kg,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,feeding_type,apgar_score,immunizations_done,reflexes_normal,risk_level
0,Sara,Female,2024-12-10,-0.627331,-0.009441,2.004203,-0.684452,0.502794,Formula,-4.539842,Yes,Yes,At Risk
1,Sara,Female,2024-12-11,-0.514655,0.634277,1.609636,0.115765,1.456862,Formula,-0.059735,No,No,At Risk
2,Sara,Female,2024-12-12,-0.514655,0.312418,-0.264557,-0.484398,-0.451274,Breastfeeding,-0.059735,No,No,Healthy
3,Sara,Female,2024-12-13,-0.305400,1.277995,-0.955049,-1.284614,-0.451274,Mixed,-0.059735,No,Yes,Healthy
4,Sara,Female,2024-12-14,-0.273207,-0.653159,-0.165915,-0.084289,-1.405342,Breastfeeding,-0.059735,No,Yes,At Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Brian,Male,2025-03-31,2.608076,-0.975018,-1.448258,0.915981,-1.405342,Formula,-0.059735,No,Yes,Healthy
2996,Brian,Male,2025-04-01,2.511497,-0.009441,-0.165915,-1.684722,0.502794,Breastfeeding,-0.059735,No,Yes,Healthy
2997,Brian,Male,2025-04-02,2.608076,-0.653159,0.327293,0.515873,0.502794,Breastfeeding,-0.059735,No,Yes,Healthy
2998,Brian,Male,2025-04-03,2.769042,1.277995,-2.040109,2.516414,-0.451274,Mixed,-0.059735,No,No,Healthy
2999,Brian,Male,2025-04-04,2.801235,-0.009441,0.425935,0.115765,-0.451274,Mixed,-0.059735,Yes,Yes,Healthy

In [34]:
df.isnull().sum()

name                    0
gender                  0
date                    0
weight_kg               0
temperature_c           0
heart_rate_bpm          0
respiratory_rate_bpm    0
oxygen_saturation       0
feeding_type            0
apgar_score             0
immunizations_done      0
reflexes_normal         0
risk_level              0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.drop_duplicates(inplace=True)

In [37]:
df.drop("name", axis=1, inplace=True)

In [38]:
df.drop("date", axis=1, inplace=True)

In [39]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["gender"] = le.fit_transform(df["gender"])

In [40]:
df["immunizations_done"] = le.fit_transform(df["immunizations_done"])

In [41]:
df["reflexes_normal"] = le.fit_transform(df["reflexes_normal"])

In [42]:
df = pd.get_dummies(df,
                    columns=["feeding_type"],
                    dtype=int)

In [43]:
df["risk_level"] = le.fit_transform(df["risk_level"])

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   gender                      3000 non-null   int64
 1   weight_kg                   3000 non-null   float64
 2   temperature_c               3000 non-null   float64
 3   heart_rate_bpm              3000 non-null   float64
 4   respiratory_rate_bpm        3000 non-null   float64
 5   oxygen_saturation           3000 non-null   float64
 6   apgar_score                 3000 non-null   float64
 7   immunizations_done          3000 non-null   int64
 8   reflexes_normal             3000 non-null   int64
 9   risk_level                  3000 non-null   int64
 10  feeding_type_Breastfeeding  3000 non-null   int64
 11  feeding_type_Formula        3000 non-null   int64
 12  feeding_type_Mixed          3000 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 304.8 KB

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X = df.drop("risk_level", axis=1)
y = df["risk_level"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [47]:
df.columns

Index(['gender', 'weight_kg', 'temperature_c', 'heart_rate_bpm',
       'respiratory_rate_bpm', 'oxygen_saturation', 'apgar_score',
       'immunizations_done', 'reflexes_normal', 'risk_level',
       'feeding_type_Breastfeeding', 'feeding_type_Formula',
       'feeding_type_Mixed'],
      dtype='object')

In [48]:
X = df.drop("risk_level", axis=1)

y = df["risk_level"]

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [50]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2400, 12)
(600, 12)
(2400,)
(600,)

In [51]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [52]:
y_pred = model.predict(X_test)

In [53]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9116666666666666

Classification Report:

              precision    recall  f1-score   support

           0       0.97      0.35      0.51        80
           1       0.91      1.00      0.95       520

    accuracy                           0.91       600
   macro avg       0.94      0.67      0.73       600
weighted avg       0.92      0.91      0.89       600


Confusion Matrix:

[[ 28  52]
 [  1 519]]

In [54]:
df.columns

Index(['gender', 'weight_kg', 'temperature_c', 'heart_rate_bpm',
       'respiratory_rate_bpm', 'oxygen_saturation', 'apgar_score',
       'immunizations_done', 'reflexes_normal', 'risk_level',
       'feeding_type_Breastfeeding', 'feeding_type_Formula',
       'feeding_type_Mixed'],
      dtype='object')

In [55]:
df.head()

,gender,weight_kg,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,apgar_score,immunizations_done,reflexes_normal,risk_level,feeding_type_Breastfeeding,feeding_type_Formula,feeding_type_Mixed
0,0,-0.627331,-0.009441,2.004203,-0.684452,0.502794,-4.539842,1,1,0,0,1,0
1,0,-0.514655,0.634277,1.609636,0.115765,1.456862,-0.059735,0,0,0,0,1,0
2,0,-0.514655,0.312418,-0.264557,-0.484398,-0.451274,-0.059735,0,0,1,1,0,0
3,0,-0.305400,1.277995,-0.955049,-1.284614,-0.451274,-0.059735,0,1,1,0,0,1
4,0,-0.273207,-0.653159,-0.165915,-0.084289,-1.405342,-0.059735,0,1,0,1,0,0

In [56]:
X = df[
[
'gender',
'weight_kg',
'temperature_c',
'heart_rate_bpm',
'respiratory_rate_bpm',
'oxygen_saturation',
'apgar_score',
'immunizations_done',
'reflexes_normal'
]
]

y = df["risk_level"]

print(X.shape)
print(y.shape)

(3000, 9)
(3000,)

In [57]:
print(df["risk_level"].unique())

[0 1]

In [58]:
print(df["risk_level"].value_counts())

risk_level
1    2602
0     398
Name: count, dtype: int64

In [59]:
df.groupby("risk_level").mean()

,gender,weight_kg,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,apgar_score,immunizations_done,reflexes_normal,feeding_type_Breastfeeding,feeding_type_Formula,feeding_type_Mixed
risk_level,,,,,,,,,,,,
0,0.562814,-0.438014,0.100541,0.359513,0.028806,-0.396140,-0.037222,0.022613,0.758794,0.324121,0.334171,0.341709
1,0.548040,0.066998,-0.015379,-0.054991,-0.004406,0.060593,0.005693,0.073405,0.761337,0.338201,0.332437,0.329362

In [60]:
df[df["risk_level"]==0].head()

,gender,weight_kg,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,apgar_score,immunizations_done,reflexes_normal,risk_level,feeding_type_Breastfeeding,feeding_type_Formula,feeding_type_Mixed
0,0,-0.627331,-0.009441,2.004203,-0.684452,0.502794,-4.539842,1,1,0,0,1,0
1,0,-0.514655,0.634277,1.609636,0.115765,1.456862,-0.059735,0,0,0,0,1,0
4,0,-0.273207,-0.653159,-0.165915,-0.084289,-1.405342,-0.059735,0,1,0,1,0,0
5,0,-0.337593,0.956136,-0.363199,-0.484398,-0.451274,-0.059735,0,1,0,0,0,1
31,0,-0.643427,-0.009441,1.215069,-0.884506,1.456862,-0.059735,0,0,0,1,0,0

In [61]:
df[df["risk_level"]==1].head()

,gender,weight_kg,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,apgar_score,immunizations_done,reflexes_normal,risk_level,feeding_type_Breastfeeding,feeding_type_Formula,feeding_type_Mixed
2,0,-0.514655,0.312418,-0.264557,-0.484398,-0.451274,-0.059735,0,0,1,1,0,0
3,0,-0.305400,1.277995,-0.955049,-1.284614,-0.451274,-0.059735,0,1,1,0,0,1
6,0,-0.224917,-0.009441,0.721860,-0.684452,0.502794,-0.059735,0,0,1,0,1,0
7,0,-0.160531,-0.975018,-0.659124,0.115765,0.502794,-0.059735,0,1,1,0,1,0
8,0,-0.257110,1.277995,-0.461841,-0.884506,-0.451274,-0.059735,0,1,1,0,0,1

In [62]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

model = RandomForestClassifier()

model.fit(X,y)

importance = pd.DataFrame({
    "feature": X.columns,
    "importance": model.feature_importances_
})

importance.sort_values(
    by="importance",
    ascending=False
)

                feature  importance
3        heart_rate_bpm    0.290998
5     oxygen_saturation    0.221449
1             weight_kg    0.204766
4  respiratory_rate_bpm    0.125107
2         temperature_c    0.108511
0                gender    0.022260
8       reflexes_normal    0.020198
7    immunizations_done    0.005837
6           apgar_score    0.000873

In [63]:
from collections import defaultdict

# Stores previous readings of each baby
baby_history = defaultdict(list)

# Stores baseline values of each baby
baby_baseline = {}

In [64]:
def update_history(baby_id, reading):
    """
    reading = {
        'heart_rate':145,
        'spo2':97,
        'resp_rate':42,
        'temperature':36.8
    }
    """

    baby_history[baby_id].append(reading)

    # Keep only last 30 readings
    if len(baby_history[baby_id]) > 30:
        baby_history[baby_id].pop(0)

In [65]:
import numpy as np

def calculate_baseline(baby_id):

    history = baby_history[baby_id]

    if len(history) < 10:
        return None

    baseline = {
        "heart_rate": np.mean([x["heart_rate"] for x in history]),
        "spo2": np.mean([x["spo2"] for x in history]),
        "resp_rate": np.mean([x["resp_rate"] for x in history]),
        "temperature": np.mean([x["temperature"] for x in history])
    }

    baby_baseline[baby_id] = baseline

    return baseline

In [66]:
def calculate_risk_score(current, baseline):

    score = 0

    if baseline is None:
        return 0

    if abs(current["heart_rate"] - baseline["heart_rate"]) > 15:
        score += 30

    if current["spo2"] < 95:
        score += 35

    if abs(current["resp_rate"] - baseline["resp_rate"]) > 10:
        score += 20

    if abs(current["temperature"] - baseline["temperature"]) > 1:
        score += 15

    return min(score,100)

In [67]:
def generate_reason(current, baseline):

    reasons=[]

    if baseline is None:
        return reasons

    if current["heart_rate"] > baseline["heart_rate"] + 15:
        reasons.append(f"Heart Rate: {current['heart_rate']} bpm ⬆️")

    elif current["heart_rate"] < baseline["heart_rate"] - 15:
        reasons.append(f"Heart Rate: {current['heart_rate']} bpm ⬇️")


    if current["spo2"] < 95:
        reasons.append(f"SpO₂: {current['spo2']}% ⬇️")


    if current["resp_rate"] > baseline["resp_rate"] + 10:
        reasons.append(f"Respiratory Rate: {current['resp_rate']}/min ⬆️")

    elif current["resp_rate"] < baseline["resp_rate"] - 10:
        reasons.append(f"Respiratory Rate: {current['resp_rate']}/min ⬇️")


    if current["temperature"] > baseline["temperature"] + 1:
        reasons.append(f"Temperature: {current['temperature']}°C ⬆️")

    elif current["temperature"] < baseline["temperature"] - 1:
        reasons.append(f"Temperature: {current['temperature']}°C ⬇️")

    return reasons

In [68]:
def determine_status(score):

    if score < 30:
        return "NORMAL"

    elif score < 70:
        return "MODERATE"

    else:
        return "CRITICAL"

In [69]:
def process_baby(baby_id, current_reading):

    # Store latest reading
    update_history(baby_id, current_reading)

    # Calculate baseline
    baseline = calculate_baseline(baby_id)

    # Until enough history is available
    if baseline is None:

        return {
            "baby_id": baby_id,
            "status": "LEARNING BASELINE"
        }

    # Risk score
    risk_score = calculate_risk_score(current_reading, baseline)

    # Status
    status = determine_status(risk_score)

    output = {
        "baby_id": baby_id,
        "status": status
    }

    if status != "NORMAL":

        output["risk_score"] = risk_score

        output["reason"] = generate_reason(
            current_reading,
            baseline
        )

    return output

In [70]:
baby = {
    "heart_rate":168,
    "spo2":93,
    "resp_rate":58,
    "temperature":36.8
}

print(process_baby("BABY_001", baby))

{'baby_id': 'BABY_001', 'status': 'LEARNING BASELINE'}

In [71]:
# Static per-baby clinical data (set once per baby, e.g. at admission)
baby_profiles = {}

def register_baby_profile(baby_id, gender, weight_kg, apgar_score,
                           immunizations_done, reflexes_normal):
    baby_profiles[baby_id] = {
        "gender": gender,
        "weight_kg": weight_kg,
        "apgar_score": apgar_score,
        "immunizations_done": immunizations_done,
        "reflexes_normal": reflexes_normal
    }

In [72]:
def calculate_trend(baby_id, window=5):
    history = baby_history[baby_id]

    if len(history) < window:
        return {"heart_rate": 0, "spo2": 0, "resp_rate": 0, "temperature": 0}

    recent = history[-window:]
    older = history[-2*window:-window] if len(history) >= 2*window else history[:window]

    def avg(readings, key):
        return np.mean([r[key] for r in readings])

    return {
        "heart_rate": avg(recent, "heart_rate") - avg(older, "heart_rate"),
        "spo2": avg(recent, "spo2") - avg(older, "spo2"),
        "resp_rate": avg(recent, "resp_rate") - avg(older, "resp_rate"),
        "temperature": avg(recent, "temperature") - avg(older, "temperature")
    }

In [73]:
rf_feature_order = list(model.feature_names_in_)

def scale_for_model(row_df):
    scaled = row_df.copy()
    for col in row_df.columns:
        if col in scaler.feature_names_in_:
            idx = list(scaler.feature_names_in_).index(col)
            scaled[col] = (row_df[col] - scaler.mean_[idx]) / scaler.scale_[idx]
    return scaled

# risk_level is binary (0/1) in this dataset, not 3-class.
# Figure out which encoded value is the "higher risk" group from the data itself.
risk_group_stats = df.groupby("risk_level")[["heart_rate_bpm", "oxygen_saturation"]].mean()
high_risk_label = risk_group_stats["oxygen_saturation"].idxmin()  # lower avg SpO2 = higher risk group
print("High-risk encoded label:", high_risk_label)
print(risk_group_stats)

def rf_predict_risk(current, profile):
    row = pd.DataFrame([{
        "gender": profile["gender"],
        "weight_kg": profile["weight_kg"],
        "temperature_c": current["temperature"],
        "heart_rate_bpm": current["heart_rate"],
        "respiratory_rate_bpm": current["resp_rate"],
        "oxygen_saturation": current["spo2"],
        "apgar_score": profile["apgar_score"],
        "immunizations_done": profile["immunizations_done"],
        "reflexes_normal": profile["reflexes_normal"]
    }])[rf_feature_order]

    row_scaled = scale_for_model(row)
    proba = model.predict_proba(row_scaled)[0]

    high_risk_idx = list(model.classes_).index(high_risk_label)
    rf_score = proba[high_risk_idx] * 100
    return rf_score

High-risk encoded label: 0
            heart_rate_bpm  oxygen_saturation
risk_level
0                 0.359513          -0.396140
1                -0.054991           0.060593

In [74]:
def clinical_safety_check(current):
    alerts = []

    if current["heart_rate"] > 200 or current["heart_rate"] < 80:
        alerts.append(f"Heart Rate: {current['heart_rate']} bpm — outside safe absolute range")

    if current["spo2"] < 85:
        alerts.append(f"SpO₂: {current['spo2']}% — critically low")

    if current["resp_rate"] > 80 or current["resp_rate"] < 20:
        alerts.append(f"Respiratory Rate: {current['resp_rate']}/min — outside safe absolute range")

    if current["temperature"] > 38.5 or current["temperature"] < 35.0:
        alerts.append(f"Temperature: {current['temperature']}°C — outside safe absolute range")

    return alerts

In [75]:
def process_baby_v2(baby_id, current_reading, profile):
    update_history(baby_id, current_reading)
    baseline = calculate_baseline(baby_id)

    if baseline is None:
        return {"baby_id": baby_id, "status": "LEARNING BASELINE"}

    baseline_score = calculate_risk_score(current_reading, baseline)
    rf_score = rf_predict_risk(current_reading, profile)
    trend = calculate_trend(baby_id)
    clinical_alerts = clinical_safety_check(current_reading)

    final_score = round(0.5 * baseline_score + 0.5 * rf_score, 1)

    if clinical_alerts:
        final_score = 100

    status = determine_status(final_score)

    output = {"baby_id": baby_id, "status": status, "risk_score": final_score}

    if status != "NORMAL":
        reasons = generate_reason(current_reading, baseline)
        reasons.extend(clinical_alerts)

        # fallback: RF flagged risk even though no single vital crossed a hard threshold
        if not reasons:
            reasons.append(f"AI model detected an unusual combination of vitals (model confidence: {round(rf_score)}%)")

        output["reason"] = reasons

    return output

In [76]:
register_baby_profile("BABY_001", gender=0, weight_kg=2.8, apgar_score=8,
                       immunizations_done=1, reflexes_normal=1)

for _ in range(15):
    process_baby_v2("BABY_001",
        {"heart_rate":146, "spo2":98, "resp_rate":42, "temperature":36.8},
        baby_profiles["BABY_001"])

print(process_baby_v2("BABY_001",
    {"heart_rate":168, "spo2":93, "resp_rate":58, "temperature":36.8},
    baby_profiles["BABY_001"]))

{'baby_id': 'BABY_001', 'status': 'CRITICAL', 'risk_score': np.float64(91.0), 'reason': ['Heart Rate: 168 bpm ⬆️', 'SpO₂: 93% ⬇️', 'Respiratory Rate: 58/min ⬆️']}

In [77]:
# Sanity check: a NORMAL reading close to baseline
print(process_baby_v2("BABY_001",
    {"heart_rate":148, "spo2":97, "resp_rate":40, "temperature":36.7},
    baby_profiles["BABY_001"]))

# Sanity check: a MODERATE reading, mild deviation
print(process_baby_v2("BABY_001",
    {"heart_rate":160, "spo2":95, "resp_rate":50, "temperature":37.0},
    baby_profiles["BABY_001"]))

{'baby_id': 'BABY_001', 'status': 'NORMAL', 'risk_score': np.float64(0.5)}
{'baby_id': 'BABY_001', 'status': 'MODERATE', 'risk_score': np.float64(48.5), 'reason': ['AI model detected an unusual combination of vitals (model confidence: 97%)']}

In [78]:
import joblib

joblib.dump(model, "model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(high_risk_label, "high_risk_label.pkl")

from google.colab import files
files.download("model.pkl")
files.download("scaler.pkl")
files.download("high_risk_label.pkl")